name: Full Stack CI/CD
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      # Frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Deploy
      - name: Deploy backend
        run: pm2 restart ubook-api
        run: pm2 restart ubook-api
